apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ais-worker-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ais-worker
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50 
