resources:
  - redis-deployment.yaml
  - ais-worker-deployment.yaml
  - https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
  - redis-service.yaml

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --kubelet-insecure-tls
    target:
      version: v1
      kind: Deployment
      name: metrics-server
      namespace: kube-system
